//@targetengine GrpL.extendScriptEngine

// Generated by UXPScriptSparker
// https://github.com/zwettemaan/UXPScriptSparker

// Generic launcher. Running this script will run the script in GryperLink.js 
// in the ExtendScript environment

if ("undefined" == typeof GrpL) {
    GrpL = {};
}

//@include "GryperLink_helpers/jsx/runtime.jsx"
GrpL.loadModules(GrpL);

